// Review.jsx — Post-meeting review screen
// Timeline scrub + synced transcript/insights + suggestions + scores

function Review({ playing, onTogglePlay, t, setT, sim }) {
  const scenario = sim.scenario;
  const total = scenario.duration;
  const events = scenario.timeline;
  const nudges = scenario.nudges;

  // Playback tick
  React.useEffect(() => {
    if (!playing) return;
    const iv = setInterval(() => {
      setT(prev => prev + 0.1 > total ? 0 : prev + 0.1);
    }, 100);
    return () => clearInterval(iv);
  }, [playing, total]);

  // Nudges up to current time for the insight column
  const insightsUpTo = nudges.filter(n => n.t <= t);
  const currentInsight = insightsUpTo[insightsUpTo.length - 1];

  return (
    <div style={{
      flex: 1, display: 'grid',
      gridTemplateColumns: '1.1fr 1.2fr 1.1fr',
      gridTemplateRows: 'auto 1fr',
      gap: 14, padding: 14, minHeight: 0,
    }}>
      {/* Top bar: scores */}
      <div style={{ gridColumn: '1 / -1' }}>
        <ScoreBar scenario={scenario}/>
      </div>

      {/* LEFT — Transcript synced */}
      <Panel eyebrow="Recording" title="Synced transcript" dense
        right={
          <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <IconButton size={26} tip={playing ? 'Pause' : 'Play'} onClick={onTogglePlay}>
              {playing ? I('pause', { size: 11 }) : I('play', { size: 11 })}
            </IconButton>
            <span className="mono" style={{ fontSize: 10.5, color: 'var(--ink-2)' }}>
              {MeetingData.fmtTime(t)} / {MeetingData.fmtTime(total)}
            </span>
          </div>
        }>
        <SyncedTranscript scenario={scenario} t={t} setT={setT}/>
      </Panel>

      {/* CENTER — Timeline + Insight */}
      <Panel eyebrow="Key moments" title="Timeline" dense>
        <Timeline scenario={scenario} events={events} total={total} t={t} setT={setT}/>
        <div style={{ padding: '10px 14px 14px', flex: 1, display: 'flex', flexDirection: 'column', gap: 10, overflowY: 'auto' }} className="scroll">
          {currentInsight ? (
            <CurrentInsight nudge={currentInsight}/>
          ) : (
            <div style={{ padding: 20, color: 'var(--ink-2)', fontSize: 12, textAlign: 'center' }}>
              Scrub to a flagged moment to see the coaching insight captured there.
            </div>
          )}

          <div>
            <div className="eyebrow" style={{ marginBottom: 8 }}>All moments</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              {events.map((e, i) => (
                <button key={i} onClick={() => setT(e.t)} style={{
                  display: 'flex', alignItems: 'center', gap: 8,
                  padding: '7px 9px', borderRadius: 6,
                  background: Math.abs(t - e.t) < 1 ? 'var(--bg-2)' : 'transparent',
                  border: '1px solid transparent',
                  borderColor: Math.abs(t - e.t) < 1 ? 'var(--line)' : 'transparent',
                  color: 'var(--ink-1)', cursor: 'pointer', textAlign: 'left',
                  width: '100%', fontFamily: 'inherit',
                  transition: 'all var(--speed)',
                }}>
                  <span style={{ width: 5, height: 5, borderRadius: '50%', background: `var(--${e.tone})` }}/>
                  <span style={{ flex: 1, fontSize: 12 }}>{e.label}</span>
                  <span className="mono" style={{ fontSize: 10.5, color: 'var(--ink-3)' }}>
                    {MeetingData.fmtTime(e.t)}
                  </span>
                </button>
              ))}
            </div>
          </div>
        </div>
      </Panel>

      {/* RIGHT — "What you could have said" */}
      <Panel eyebrow="Coaching" title="What you could have said" dense>
        <div className="scroll" style={{ flex: 1, overflowY: 'auto', padding: '10px 14px 14px', display: 'flex', flexDirection: 'column', gap: 10 }}>
          {nudges.filter(n => n.action).length === 0 && (
            <div style={{ padding: 20, color: 'var(--ink-2)', fontSize: 12, textAlign: 'center' }}>
              No rewrite suggestions for this meeting — you handled the moments well.
            </div>
          )}
          {nudges.filter(n => n.action).map(n => (
            <CoachCard key={n.id} nudge={n} active={Math.abs(t - n.t) < 3} onJump={() => setT(n.t)}/>
          ))}

          <div style={{
            marginTop: 6,
            padding: 12,
            background: 'var(--bg-inset)',
            border: '1px solid var(--line-soft)',
            borderRadius: 8,
            display: 'flex', gap: 10,
          }}>
            <span style={{ color: 'var(--blue)', marginTop: 1 }}>{I('info', { size: 14 })}</span>
            <div style={{ fontSize: 11.5, color: 'var(--ink-1)', lineHeight: 1.5 }}>
              Talksmith's suggestions are generated by comparing your patterns to high-influence meetings
              you've previously tagged as successful. Each is <b>explainable</b> — hover any score to see
              the contributing signals.
            </div>
          </div>
        </div>
      </Panel>
    </div>
  );
}

function ScoreBar({ scenario }) {
  // Real, scenario-derived scores. Memoized so we don't re-analyze the
  // transcript on every playback tick.
  const result = React.useMemo(() => MeetingData.scoreScenario(scenario), [scenario]);
  const { signals, tones } = result;
  const scores = [
    { k: 'Talk ratio', v: result.talkRatio, unit: '%',    target: '<50', tone: tones.talkRatio, hint: signals.talkRatio },
    { k: 'Clarity',    v: result.clarity,   unit: '/100', target: '>75', tone: tones.clarity,   hint: signals.clarity },
    { k: 'Influence',  v: result.influence, unit: '/100', target: '>70', tone: tones.influence, hint: signals.influence },
    { k: 'Listening',  v: result.listening, unit: '/100', target: '>70', tone: tones.listening, hint: signals.listening },
  ];
  const gradeTone = result.overall >= 75 ? 'green' : result.overall >= 60 ? 'amber' : 'rose';
  return (
    <div data-testid="score-bar" style={{
      display: 'grid', gridTemplateColumns: 'repeat(4, 1fr) auto',
      gap: 1, background: 'var(--line)',
      border: '1px solid var(--line)', borderRadius: 'var(--radius-lg)',
      overflow: 'hidden',
    }}>
      {scores.map((s, i) => (
        <div key={i} data-testid={`score-${s.k.toLowerCase().replace(/\s+/g, '-')}`}
          title={s.hint.join(' · ')}
          style={{ background: 'var(--bg-1)', padding: '12px 16px', cursor: 'help' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 4 }}>
            <span className="eyebrow">{s.k}</span>
            <span style={{ fontSize: 9.5, color: 'var(--ink-3)', fontFamily: 'var(--font-mono)' }}>target {s.target}</span>
          </div>
          <div style={{ display: 'flex', alignItems: 'baseline', gap: 3 }}>
            <span className="mono" data-testid={`score-value-${s.k.toLowerCase().replace(/\s+/g, '-')}`} style={{
              fontSize: 26, fontWeight: 600, letterSpacing: '-0.03em',
              color: `var(--${s.tone})`,
            }}>{s.v}</span>
            <span style={{ fontSize: 11, color: 'var(--ink-2)' }}>{s.unit}</span>
          </div>
          <div style={{ marginTop: 6 }}>
            <Meter value={s.v} max={100} color={`var(--${s.tone})`} height={3}/>
          </div>
          {/* Top contributing signal, always visible (explainability) */}
          <div style={{ fontSize: 10, color: 'var(--ink-3)', marginTop: 6, lineHeight: 1.35 }}>
            {s.hint[0]}
          </div>
        </div>
      ))}
      <div style={{ background: 'var(--bg-1)', padding: '12px 18px', display: 'flex', alignItems: 'center', gap: 14 }}>
        <div style={{ display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: 3 }}>
          <span className="eyebrow">Meeting</span>
          <div style={{ fontSize: 13, fontWeight: 600 }}>{scenario.name}</div>
          <div style={{ fontSize: 11, color: 'var(--ink-2)' }}>
            {MeetingData.fmtTime(scenario.duration)} · {scenario.participants.length} participants
          </div>
        </div>
        {/* Composite grade */}
        <div data-testid="meeting-grade" title={`Overall ${result.overall}/100`} style={{
          width: 52, height: 52, borderRadius: 12, flexShrink: 0,
          display: 'grid', placeItems: 'center',
          background: `var(--${gradeTone}-soft)`,
          border: `1px solid var(--${gradeTone}-line, var(--line))`,
          color: `var(--${gradeTone})`,
        }}>
          <span className="mono" style={{ fontSize: 24, fontWeight: 700, letterSpacing: '-0.03em' }}>
            {result.grade}
          </span>
        </div>
      </div>
    </div>
  );
}

function SyncedTranscript({ scenario, t, setT }) {
  const scrollRef = React.useRef();
  const activeRef = React.useRef();
  const script = scenario.script;
  const activeIdx = script.findLastIndex(l => l.t <= t);

  React.useEffect(() => {
    if (activeRef.current && scrollRef.current) {
      const el = activeRef.current;
      const parent = scrollRef.current;
      parent.scrollTop = el.offsetTop - parent.offsetHeight / 2 + el.offsetHeight / 2;
    }
  }, [activeIdx]);

  return (
    <div ref={scrollRef} className="scroll" style={{
      flex: 1, overflowY: 'auto', padding: '8px 16px 14px', minHeight: 0,
    }}>
      {script.map((l, i) => {
        const speaker = scenario.participants.find(p => p.id === l.s);
        const active = i === activeIdx;
        const past = l.t < t;
        return (
          <div key={i} ref={active ? activeRef : null}
               onClick={() => setT(l.t)}
               style={{
                 padding: '8px 10px',
                 margin: '2px 0',
                 borderRadius: 6,
                 background: active ? 'var(--bg-2)' : 'transparent',
                 border: '1px solid transparent',
                 borderColor: active ? 'var(--line)' : 'transparent',
                 cursor: 'pointer',
                 opacity: past ? 1 : 0.45,
                 transition: 'all var(--speed)',
               }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 3 }}>
              <span style={{ width: 5, height: 5, borderRadius: '50%', background: speaker.color }}/>
              <span style={{ fontSize: 11, fontWeight: 600, color: l.s === 'you' ? 'var(--ink-0)' : 'var(--ink-1)' }}>
                {speaker.name}
              </span>
              <span className="mono" style={{ fontSize: 10, color: 'var(--ink-3)' }}>
                {MeetingData.fmtTime(l.t)}
              </span>
              {l.interrupted && <Chip tone="rose" size="sm">interrupted</Chip>}
            </div>
            <div style={{ fontSize: 12.5, color: active ? 'var(--ink-0)' : 'var(--ink-1)', lineHeight: 1.5, paddingLeft: 11, textWrap: 'pretty' }}>
              {l.txt}
            </div>
          </div>
        );
      })}
    </div>
  );
}

function Timeline({ scenario, events, total, t, setT }) {
  const barRef = React.useRef();
  const handleClick = (e) => {
    const rect = barRef.current.getBoundingClientRect();
    const pct = (e.clientX - rect.left) / rect.width;
    setT(Math.max(0, Math.min(total, pct * total)));
  };
  // Synthetic waveform
  const bars = React.useMemo(() => Array.from({ length: 120 }, (_, i) => {
    const speechHeight = 0.3 + 0.7 * Math.abs(Math.sin(i * 0.43) * Math.cos(i * 0.19 + 1.3));
    return speechHeight;
  }), []);

  return (
    <div style={{ padding: '12px 14px 10px', borderBottom: '1px solid var(--line-soft)' }}>
      {/* Speaker lanes */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 3, marginBottom: 8 }}>
        {scenario.participants.map(p => {
          const segments = scenario.script.filter(l => l.s === p.id).map(l => ({
            start: l.t / total * 100,
            width: Math.min(100, (l.txt.split(/\s+/).length / 145 * 60) / total * 100),
          }));
          return (
            <div key={p.id} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <span style={{
                width: 28, fontSize: 9.5, color: 'var(--ink-2)',
                fontFamily: 'var(--font-mono)',
              }}>{p.initials}</span>
              <div style={{
                position: 'relative', flex: 1, height: 6,
                background: 'var(--bg-inset)', borderRadius: 3,
              }}>
                {segments.map((seg, i) => (
                  <div key={i} style={{
                    position: 'absolute', left: `${seg.start}%`, width: `${seg.width}%`,
                    top: 0, bottom: 0, background: p.color, opacity: 0.5, borderRadius: 2,
                  }}/>
                ))}
              </div>
            </div>
          );
        })}
      </div>

      {/* Waveform + events */}
      <div ref={barRef} onClick={handleClick} style={{
        position: 'relative', height: 44, cursor: 'pointer',
        background: 'var(--bg-inset)', borderRadius: 6,
        padding: '6px 4px',
        userSelect: 'none',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 1, height: '100%' }}>
          {bars.map((h, i) => {
            const atT = (i / bars.length) * total;
            const past = atT <= t;
            return (
              <div key={i} style={{
                flex: 1, height: `${h * 100}%`,
                background: past ? 'var(--ink-1)' : 'var(--line-strong)',
                borderRadius: 0.5,
                transition: 'background var(--speed)',
              }}/>
            );
          })}
        </div>

        {/* Event flags */}
        {events.map((e, i) => (
          <div key={i} onClick={(ev) => { ev.stopPropagation(); setT(e.t); }}
               style={{
                 position: 'absolute', left: `${(e.t / total) * 100}%`,
                 top: -3, bottom: -3,
                 width: 2, background: `var(--${e.tone})`,
                 transform: 'translateX(-50%)',
                 cursor: 'pointer',
               }}
               title={`${e.label} · ${MeetingData.fmtTime(e.t)}`}>
            <div style={{
              position: 'absolute', top: -5, left: '50%', transform: 'translateX(-50%)',
              width: 8, height: 8, borderRadius: '50%',
              background: `var(--${e.tone})`, border: '2px solid var(--bg-1)',
            }}/>
          </div>
        ))}

        {/* Playhead */}
        <div style={{
          position: 'absolute', left: `${(t / total) * 100}%`,
          top: -4, bottom: -4, width: 2,
          background: 'var(--ink-0)', transform: 'translateX(-50%)',
          pointerEvents: 'none',
        }}>
          <div style={{
            position: 'absolute', top: -6, left: '50%', transform: 'translateX(-50%)',
            width: 10, height: 10, background: 'var(--ink-0)', borderRadius: 2,
          }}/>
        </div>
      </div>

      <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 5, fontSize: 10, color: 'var(--ink-3)', fontFamily: 'var(--font-mono)' }}>
        <span>00:00</span>
        <span>{MeetingData.fmtTime(total / 2)}</span>
        <span>{MeetingData.fmtTime(total)}</span>
      </div>
    </div>
  );
}

function CurrentInsight({ nudge }) {
  return (
    <div style={{
      padding: 12,
      background: `var(--${nudge.tone}-soft)`,
      border: `1px solid var(--${nudge.tone}-line)`,
      borderRadius: 8,
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
        <span style={{ width: 6, height: 6, borderRadius: '50%', background: `var(--${nudge.tone})` }}/>
        <span className="eyebrow" style={{ color: `var(--${nudge.tone})` }}>{nudge.type}</span>
        <span className="mono" style={{ fontSize: 10, color: 'var(--ink-2)' }}>at {MeetingData.fmtTime(nudge.t)}</span>
        <div style={{ flex: 1 }}/>
        <Confidence level={nudge.confidence}/>
      </div>
      <div style={{ fontSize: 13.5, fontWeight: 600, marginBottom: 3 }}>{nudge.title}</div>
      <div style={{ fontSize: 12, color: 'var(--ink-1)', lineHeight: 1.5 }}>{nudge.detail}</div>
      {nudge.signals && (
        <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap', marginTop: 8 }}>
          {nudge.signals.map((s, i) => (
            <span key={i} className="mono" style={{
              fontSize: 10.5, color: 'var(--ink-2)',
              padding: '2px 6px', background: 'var(--bg-1)',
              border: '1px solid var(--line-soft)', borderRadius: 4,
            }}>{s}</span>
          ))}
        </div>
      )}
    </div>
  );
}

function CoachCard({ nudge, active, onJump }) {
  return (
    <div style={{
      padding: 12,
      background: active ? 'var(--bg-2)' : 'var(--bg-1)',
      border: '1px solid',
      borderColor: active ? `var(--${nudge.tone}-line)` : 'var(--line-soft)',
      borderRadius: 8,
      transition: 'all var(--speed)',
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
        <span style={{ width: 5, height: 5, borderRadius: '50%', background: `var(--${nudge.tone})` }}/>
        <span style={{ fontSize: 11.5, fontWeight: 500, color: 'var(--ink-1)' }}>{nudge.title}</span>
        <div style={{ flex: 1 }}/>
        <button onClick={onJump} className="mono" style={{
          border: 'none', background: 'transparent', color: 'var(--ink-2)',
          fontSize: 10.5, cursor: 'pointer', padding: 0,
        }}>jump ↗</button>
      </div>
      <div style={{
        padding: '9px 11px',
        background: 'var(--bg-inset)',
        border: '1px solid var(--line-soft)',
        borderRadius: 6,
        fontSize: 12.5, fontStyle: 'italic', color: 'var(--ink-0)',
        lineHeight: 1.5,
      }}>
        {nudge.action.phrase}
      </div>
      <div style={{ marginTop: 6, fontSize: 10.5, color: 'var(--ink-3)', fontFamily: 'var(--font-mono)' }}>
        at {MeetingData.fmtTime(nudge.t)} · instead of what you said
      </div>
    </div>
  );
}

window.Review = Review;
